server:
  port: 8080
spring:
  application:
    name: service_edu
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
  #返回数据统一时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#日志配置
logging:
  config: classpath:logback.xml
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error #swagger2.9.2版本实体类注解@ApiModelProperty为int类型时导致
#配置控制台打印sql及其结果
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl